export const defaultAppContext = {
  forceStartScreen: null,
  forceStartCamera: null,
  behavior: {},
  l10n: {
    // Text defaults from app.js
    title: 'Interactive Explorer',
    playAudioTrack: 'Play Audio Track',
    pauseAudioTrack: 'Pause Audio Track',
    sceneDescription: 'Scene Description',
    resetCamera: 'Reset Camera',
    submitDialog: 'Submit Dialog',
    closeDialog: 'Close Dialog',
    expandButtonAriaLabel: 'Expand the visual label',
    goToStartScene: 'Go to start scene',
    userIsAtStartScene: 'You are at the start scene',
    unlocked: 'Unlocked',
    locked: 'Locked',
    searchRoomForCode: 'Search the room until you find the code',
    wrongCode: 'The code was wrong, try again.',
    contentUnlocked: 'The content has been unlocked!',
    code: 'Code',
    showCode: 'Show code',
    hideCode: 'Hide code',
    unlockedStateAction: 'Continue',
    lockedStateAction: 'Unlock',
  },
  params: {},
  contentId: 0,
  extras: {},
  sceneRenderingQuality: "high",
  on: () => undefined,
};
